<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 /Users/sejmou/Repos/misc/notes-website/tmp/stylised_chromebook_laptop_computer/scene.gltf --transform
Author: Sophuwu (https://sketchfab.com/Sophuwu)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/stylised-chromebook-laptop-computer-d55ed81fdaf241378a3f0c33d25358aa
Title: Stylised Chromebook Laptop Computer
-->

<script>
  import { Group } from 'three';
  import { T, forwardEventHandlers } from '@threlte/core';
  import { useGltf, useGltfAnimations } from '@threlte/extras';

  export const ref = new Group();

  const gltf = useGltf('/models/laptop.glb', { useDraco: true });
  export const { actions, mixer } = useGltfAnimations(gltf, ref);

  const component = forwardEventHandlers();
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <!-- adjusted scale manually as object is pretty small -->
    <T.Group name="Sketchfab_Scene" scale={[10, 10, 10]}>
      <T.Group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
        <T.Group name="root">
          <T.Group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
            <T.Group name="Armature_3" position={[0, 0.01, -0.1]}>
              <T.Group name="GLTF_created_0">
                <T is={gltf.nodes.GLTF_created_0_rootJoint} />
                <T.SkinnedMesh
                  name="Object_7"
                  geometry={gltf.nodes.Object_7.geometry}
                  material={gltf.materials.Material}
                  skeleton={gltf.nodes.Object_7.skeleton}
                />
                <T.SkinnedMesh
                  name="Object_8"
                  geometry={gltf.nodes.Object_8.geometry}
                  material={gltf.materials['Material.001']}
                  skeleton={gltf.nodes.Object_8.skeleton}
                />
                <T.SkinnedMesh
                  name="Object_9"
                  geometry={gltf.nodes.Object_9.geometry}
                  material={gltf.materials['Material.002']}
                  skeleton={gltf.nodes.Object_9.skeleton}
                />
                <T.SkinnedMesh
                  name="Object_10"
                  geometry={gltf.nodes.Object_10.geometry}
                  material={gltf.materials['Material.003']}
                  skeleton={gltf.nodes.Object_10.skeleton}
                />
                <T.SkinnedMesh
                  name="Object_11"
                  geometry={gltf.nodes.Object_11.geometry}
                  material={gltf.materials['Material.004']}
                  skeleton={gltf.nodes.Object_11.skeleton}
                />
                <T.SkinnedMesh
                  name="Object_12"
                  geometry={gltf.nodes.Object_12.geometry}
                  material={gltf.materials['Material.005']}
                  skeleton={gltf.nodes.Object_12.skeleton}
                />
              </T.Group>
            </T.Group>
          </T.Group>
        </T.Group>
      </T.Group>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
